/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import java.awt.Container;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class Juego extends javax.swing.JFrame {

    Palabra maiGuord=new Palabra();
    String palabraJugada="Hola";
    JLabel espacio[];
    Font fuente=new Font("Calibri",2,30);
    Container miContenedor=new Container();
    boolean juegoEnCurso=false;
    File miArchivo=new File("Monacho.jpg");
    JLabel parteImagen[]=new JLabel[5];
    Imagen muñeco = new Imagen();
    int contMalas;
    
    
    public Juego() {
        initComponents();
        espacio=new JLabel[palabraJugada.length()];
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i]=new JLabel();
        }
        for(int i=0;i<5;i++){
            parteImagen[i]=new JLabel();
            parteImagen[i].setBounds(30,50+(i*50),200,50);
            add(parteImagen[i]);
            try {
                BufferedImage miImagen = ImageIO.read(miArchivo);
                BufferedImage miniImagen = miImagen.getSubimage(0,50*i,200,50);
                ImageIcon miIcono = new ImageIcon(miniImagen);
                parteImagen[i].setIcon(miIcono);
                parteImagen[i].setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        invisibilizar();
    }
    void invisibilizar(){
        Etiqueta.setVisible(false);
        oquei.setVisible(false);
        palabra.setVisible(false);
        Etiqueta1.setVisible(false);
        sí.setVisible(false);
        Etiqueta2.setVisible(false);
        jugadas.setText("");
        jugadas.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiqueta = new javax.swing.JLabel();
        palabra = new javax.swing.JTextField();
        oquei = new javax.swing.JButton();
        Etiqueta1 = new javax.swing.JLabel();
        sí = new javax.swing.JButton();
        Etiqueta2 = new javax.swing.JLabel();
        jugadas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        Etiqueta.setText("¿Ya Sabes la palabra?");

        oquei.setText("OK");
        oquei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oqueiMouseClicked(evt);
            }
        });

        Etiqueta1.setText("Si te equivocas pierdes");

        sí.setText("Conozco la palabra");
        sí.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                síMouseClicked(evt);
            }
        });

        Etiqueta2.setText("Letras Jugadas:");

        jugadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jugadas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jMenu1.setText("Iniciar Juego");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Etiqueta2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jugadas, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(Etiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(oquei)
                                .addComponent(sí)
                                .addComponent(palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Etiqueta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sí, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oquei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Etiqueta2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jugadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i].setVisible(false);
        }
        palabraJugada=maiGuord.seleccionarPalabra();
        espacio=new JLabel[palabraJugada.length()];
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i]=new JLabel();
            espacio[i].setBounds(30*i,10,30,30);
            espacio[i].setFont(fuente);
            add(espacio[i]);
            espacio[i].setText("_");
        }
        for(int i=0;i<5;i++){
            parteImagen[i].setVisible(false);
        }
        juegoEnCurso=true;
        contMalas=0;
        Etiqueta.setVisible(true);
        Etiqueta1.setVisible(true);
        sí.setVisible(true);
        Etiqueta2.setVisible(true);
        jugadas.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        char tecla = evt.getKeyChar();
        boolean letraCorrecta=false;
        if(juegoEnCurso==true){
            jugadas.setText(jugadas.getText() + String.valueOf(tecla) + " ");
            if(tecla>='a'&&tecla<='z'||tecla>='A'&&tecla<='Z'||tecla=='ñ'||tecla=='Ñ'){
                for(int i=0;i<palabraJugada.length();i++){
                    if(String.valueOf(tecla).equalsIgnoreCase(palabraJugada.substring(i, i+1))){
                        espacio[i].setText(palabraJugada.substring(i, i+1));
                        letraCorrecta=true;
                    }
                }
                if(letraCorrecta==false){
                    parteImagen[contMalas].setVisible(true);
                    if(contMalas==4){
                        for(int i=0;i<palabraJugada.length();i++){
                            espacio[i].setText(palabraJugada.substring(i, i+1));
                        }
                        JOptionPane.showMessageDialog(this, "PERDISTE");
                        juegoEnCurso=false;
                        invisibilizar();
                    }else{
                        contMalas++;
                    }
                }else{
                    int cuentaEspacios=0;
                    for(int i=0;i<palabraJugada.length();i++){
                        if("_".equals(espacio[i].getText())){
                            cuentaEspacios++;
                        }
                    }
                    if(cuentaEspacios==0){
                        JOptionPane.showMessageDialog(this, "GANASTE");
                        juegoEnCurso=false;
                        invisibilizar();
                    }
                }
            }
            else
            {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_formKeyTyped

    private void oqueiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oqueiMouseClicked
        if(palabra.getText().equalsIgnoreCase(palabraJugada)){
            for(int i=0;i<palabraJugada.length();i++){
                espacio[i].setText(palabraJugada.substring(i, i+1));
            }
            JOptionPane.showMessageDialog(this, "GANASTE");
            juegoEnCurso=false;
            invisibilizar();
        }else{
            for(int i=0;i<palabraJugada.length();i++){
                espacio[i].setText(palabraJugada.substring(i, i+1));
            }
            JOptionPane.showMessageDialog(this, "PERDISTE");
            juegoEnCurso=false;
            invisibilizar();
        }
    }//GEN-LAST:event_oqueiMouseClicked

    private void síMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_síMouseClicked
        palabra.setVisible(true);
        oquei.setVisible(true);
    }//GEN-LAST:event_síMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JLabel Etiqueta1;
    private javax.swing.JLabel Etiqueta2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jugadas;
    private javax.swing.JButton oquei;
    private javax.swing.JTextField palabra;
    private javax.swing.JButton sí;
    // End of variables declaration//GEN-END:variables
}

