/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import java.awt.Container;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Estudiantes
 */
public class Juego extends javax.swing.JFrame {

    Palabra maiGuord=new Palabra();
    String palabraJugada="Hola";
    JLabel espacio[];
    Font fuente=new Font("Calibri",2,30);
    Container miContenedor=new Container();
    boolean juegoEnCurso=false;
    File miArchivo=new File("Monacho.jpg");
    JLabel parteImagen[]=new JLabel[5];
    Imagen muñeco = new Imagen();
    
    
    public Juego() {
        initComponents();
        espacio=new JLabel[palabraJugada.length()];
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i]=new JLabel();
        }
        for(int i=0;i<5;i++){
            parteImagen[i]=new JLabel();
            parteImagen[i].setBounds(30,50+(i*50),200,50);
            add(parteImagen[i]);
            try {
                BufferedImage miImagen = ImageIO.read(miArchivo);
                BufferedImage miniImagen = miImagen.getSubimage(0,50*i,200,50);
                ImageIcon miIcono = new ImageIcon(miniImagen);
                parteImagen[i].setIcon(miIcono);
                parteImagen[i].setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jMenu1.setText("Iniciar Juego");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i].setVisible(false);
        }
        palabraJugada=maiGuord.seleccionarPalabra();
        espacio=new JLabel[palabraJugada.length()];
        for(int i=0;i<palabraJugada.length();i++){
            espacio[i]=new JLabel();
            espacio[i].setBounds(30*i,10,30,30);
            espacio[i].setFont(fuente);
            add(espacio[i]);
            espacio[i].setText("_");
        }
        juegoEnCurso=true;
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        char tecla = evt.getKeyChar();
        boolean letraCorrecta=false;
        if(juegoEnCurso==true){
            if(tecla>='a'&&tecla<='z'||tecla>='A'&&tecla<='Z'){
                for(int i=0;i<palabraJugada.length();i++){
                    if(String.valueOf(tecla).equalsIgnoreCase(palabraJugada.substring(i, i+1))){
                        espacio[i].setText(palabraJugada.substring(i, i+1));
                        letraCorrecta=true;
                    }
                }
                if(letraCorrecta==false){
                    System.out.println("Mal");
                }
            }
            else
            {
                evt.consume();
            }
        }
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}

